# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('cmsplugin_zinnia', '0005_auto_20170809_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZinniaAppInstancePlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_zinnia_zinniaappinstanceplugin', serialize=False, to='cms.CMSPlugin')),
                ('app', models.CharField(blank=True, choices=[('', '-------'), ('blog', 'Blog'), ('press', 'Press')], db_index=True, default='', max_length=50, verbose_name='application')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
